name: bcr-bulk-demo
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - ipykernel
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - sra-tools
  - trust4
  - pigz
